routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('/categories','Category\CategoryController');
Route::Resource('/posts','Post\PostController');
Route::Resource('/tags','Tag\TagController');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['post_id','name'];
    public function posts() {
        return $this->belongsToMany(Post::class);
    }
    protected static function boot() {
        parent::boot();
        static::deleting(function($offer) {
            $offer->posts()->delete();
            $offer->posts()->detach();
        });
    }


}

app/Http/Controllers/Tag/TagController.php
<?php

namespace App\Http\Controllers\Tag;

use App\Contracts\PostInterface;
use App\Http\Requests\TagCreate;
use App\Repositories\TagRepo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Contracts\TagInterface;
class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $tagRepo;
    protected $postRepo;

    public function __construct(TagInterface $tag, PostInterface $post)
    {

        $this->tagRepo = $tag;
        $this->postRepo = $post;
    }

    public function index()
    {
        $tags = $this->tagRepo->all();
        return view('tags.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $posts = $this->postRepo->all();
        return view('tags.create',compact('posts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagCreate $request)
    {
        $this->tagRepo->store($request);
        return redirect('tags')->with('message','Tag created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $posts = $this->postRepo->getPosts();
        $tag = $this->tagRepo->find($id);
        return view('tags.edit',compact('tag','posts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagCreate $request, $id)
    {
       if($this->tagRepo->update($id,$request)){
           return redirect('tags')->with('message','Tag updated ');
       }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if($this->tagRepo->delete($id)) {
            return response()->json(['id'=> $id]);
        }
        //
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="box box-info col-8">
                <div class="box-header with-border">
                    <h3 class="box-title">Horizontal Form</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('tags.store')}}" method="POST">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="Name" name="name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Select Post</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="post_id[]" multiple="multiple">
                                    @foreach($posts as $post)
                                        <option value="{{$post->id}}">{{$post->title}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{route('tags.index')}}"  class="btn btn-default">Back</a>
                            <button type="submit" class="btn btn-info pull-right">Add</button>
                            @if(session('message'))
                                <div class="alert-success mt-2 p-2">
                                    {{session('message')}}
                                </div>
                            @endif
                            @if($errors->any())
                                <div class="alert-danger mt-2 p-2">
                                    {{$errors->first()}}
                                </div>
                            @endif
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="box box-info col-8">
                <div class="box-header with-border">
                    <h3 class="box-title">Horizontal Form</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('tags.update',$tag->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="Name" name="name" value="{{$tag->name}}">
                            </div>
                        </div>


                        <div class="form-group"><label class="col-sm-2 control-label">Select</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="post_id[]" multiple="multiple">
                                    @foreach($posts as $post)
                                        <option value="{{$post->id}} " {{$tag->posts->find($post->id)?' selected':''}}>{{$post->title}}</option>
                                    @endforeach
                                </select>
                            </div>

                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{route('tags.index')}}"  class="btn btn-default">Back</a>
                            <button type="submit" class="btn btn-info pull-right">Update</button>
                            @if(session('message'))
                                <div class="alert-success mt-2 p-2">
                                    {{session('message')}}
                                </div>
                            @endif
                            @if($errors->any())
                                <div class="alert-danger mt-2 p-2">
                                    {{$errors->first()}}
                                </div>
                            @endif

                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')
@section('content')

    <div id="example2_wrapper" class="dataTables_wrapper  dt-bootstrap mt-5">
        <div class="clearfix">
            <h4 class="d-inline-block">Tag table</h4>
            <a href="{{route('tags.create')}}" class="btn btn-info pull-right"> Add Tag</a>
        </div>

        <div class  ="row">
            <div class="col-sm-6">
                @if(session('message'))
                    <div class="alert-success mt-2 p-2">
                        {{session('message')}}
                    </div>
                @endif
                @if($errors->any())
                    <div class="alert-success mt-2 p-2">
                        {{$errors->first()}}
                    </div>
                @endif
            </div>
            <div class="col-sm-6"></div>
        </div>
        @if($tags->first())
            <div class="row justify-content-center mt-3">
                <div class="col-sm-12">
                    <table id="example2" class="table table-bordered table-hover dataTable box box-info" role="grid" aria-describedby="example2_info">
                        <thead>
                        <tr role="row">
                            <th>Id</th>
                            <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" aria-sort="descending">Name</th>
                            <th> Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($tags as $tag)
                            <tr role="row"  data-get="{{$tag->id}}">
                                <td>{{$tag->id}}</td>
                                <td class="sorting_1"><a href="{{route('tags.edit',$tag->id)}}">{{$tag->name}}</a>
                                <td ><a href="{{route('tags.destroy',$tag->id)}}" class="btn btn-danger destroy" data-method="delete"  data-id="{{$tag->id}}">Delete</a></td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-5">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                </div>
                <div class="col-sm-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                        <ul class="pagination">
                            <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                            <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>
                            <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                        </ul>
                    </div>
                </div>
            </div>
    </div>
    @else
        <div class="alert-info p-3">
            You don't have now any tags please add
        </div>
    @endif
@endsection