routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('/categories','Category\CategoryController');
Route::Resource('/posts','Post\PostController');
Route::Resource('/tags','Tag\TagController');

app/Models/Post.php
<?php

namespace App\Models;

use App\Models\Image;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected  $fillable =['category_id','title','description'];
    public function tags() {
        return $this->belongsToMany(Tag::class);
    }
    public function images() {
        return $this->hasMany(Image::class);
    }
    public function category() {
        return $this->belongsTo(Category::class);
    }
    //delete child tags

    protected static function boot() {
        parent::boot();
        static::deleting(function($offer) {
            $offer->tags()->delete();
            $offer->tags()->detach();
            $offer->images()->delete();
        });
    }



}

app/Http/Controllers/Post/Images/ImageController.php
<?php

namespace App\Http\Controllers\Post\Images;

use App\Http\Requests\ImageCreate;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ImageCreate $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Post/PostController.php
<?php

namespace App\Http\Controllers\Post;

use App\Contracts\CategoryInterface;
use App\Contracts\PostInterface;
use App\Http\Requests\PostCreate;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $postRepo;
    protected $categoryRepo;
    public function __construct(PostInterface $post,CategoryInterface $category)
    {
        $this->postRepo = $post;
        $this->categoryRepo = $category;
    }

    public function index()
    {
        $posts = $this->postRepo->getPosts();
        return view('posts.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories =  $this->categoryRepo->all();
        return view('posts.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostCreate $request)
    {
            $this->postRepo->store($request);
            return redirect('posts')->with('message','Post Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //CategoryInterface
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = $this->postRepo->find($id);
        $categories = $this->categoryRepo->all();
        return view('posts.edit',compact('post','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostCreate $request, $id)
    {
        $post = $this->postRepo->update($id, $request);
        return redirect('posts')->with('message','Post updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

       if($this->postRepo->delete($id)) {
         return response()->json(['id'=>$id]);
       }
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="box box-info col-8">
                <div class="box-header with-border">
                    <h3 class="box-title">Horizontal Form</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="Name" name="title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Description</label>
                            <div class="col-sm-10">
                                <textarea name="description"  class="form-control" placeholder="description"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Select</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="category_id">
                                    @foreach($categories as $category )
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <div class="col-sm-10 float-right">
                                <input type="file" id="exampleInputFile" name="path[]" multiple="multiple">
                                <p class="help-block">Upload file</p>
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{route('posts.index')}}"  class="btn btn-default">Back</a>
                            <button type="submit" class="btn btn-info pull-right">Add</button>
                            @if(session('message'))
                                <div class="alert-success mt-2 p-2">
                                    {{session('message')}}
                                </div>
                            @endif
                            @if($errors->any())
                                <div class="alert-danger mt-2 p-2">
                                    {{$errors->first()}}
                                </div>
                            @endif
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="box box-info col-8">
                <div class="box-header with-border">
                    <h3 class="box-title">Horizontal Form</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->

                <form class="form-horizontal" action="{{route('posts.update',$post->id)}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="Name" name="title" value="{{$post->title}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Description</label>
                            <div class="col-sm-10">
                                <textarea name="description"  class="form-control" placeholder="description">{{$post->description}}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Select</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="category_id">
                                    @foreach($categories as $category )
                                        <option value="{{$category->id}}" {{$post->category_id == $category->id ?' selected':''}}>{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <div class="col-sm-10 float-right">
                                <input type="file" id="exampleInputFile" name="path[]" multiple="multiple">
                                <p class="help-block">Upload file</p>
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{route('posts.index')}}"  class="btn btn-default">Back</a>
                            <button type="submit" class="btn btn-info pull-right">Update</button>
                            @if(session('message'))
                                <div class="alert-success mt-2 p-2">
                                    {{session('message')}}
                                </div>
                            @endif
                            @if($errors->any())
                                <div class="alert-danger mt-2 p-2">
                                    {{$errors->first()}}
                                </div>
                            @endif
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>
                <div class="container mt-5">

                    <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Thumbnail Gallery</h1>

                    <hr class="mt-2 mb-5">

                    <div class="row text-center text-lg-left">
                        @foreach($post->images as $image)
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="{{asset('storage/'.$image->path)}}" alt="">
                            </a>
                        </div>

                        @endforeach

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')

    <div id="example2_wrapper" class="dataTables_wrapper  dt-bootstrap mt-5">
        <div class="clearfix">
            <h4 class="d-inline-block">Post table</h4>
            <a href="{{route('posts.create')}}" class="btn btn-info pull-right"> Add Post</a>
        </div>

        <div class  ="row">
            <div class="col-sm-6">
                @if(session('message'))
                    <div class="alert-success mt-2 p-2">
                        {{session('message')}}
                    </div>
                @endif
                @if($errors->any())
                    <div class="alert-success mt-2 p-2">
                        {{$errors->first()}}
                    </div>
                @endif
            </div>
            <div class="col-sm-6"></div>
        </div>
        @if($posts->first())
            <div class="row justify-content-center mt-3">
                <div class="col-sm-12">
                    <table id="example2" class="table table-bordered table-hover dataTable box box-info" role="grid" aria-describedby="example2_info">
                        <thead>
                        <tr role="row">
                            <th>Id</th>
                            <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" aria-sort="descending">Name</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Description</th>
                            <th> Category</th>
                            <th> Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($posts as $post)
                            <tr role="row"  data-get="{{$post->id}}">
                                <td>{{$post->id}}</td>
                                <td class="sorting_1"><a href="{{route('posts.edit',$post->id)}}">{{$post->title}}</a>
                                <td>{{$post->description}}</td>
                                <td>{{$post->category->name}}</td>
                                <td ><a href="{{route('posts.destroy',$post->id)}}" class="btn btn-danger destroy" data-method="delete"  data-id="{{$post->id}}">Delete</a></td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-5">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                </div>
                <div class="col-sm-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                        <ul class="pagination">
                            <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                            <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>
                            <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                        </ul>
                    </div>
                </div>
            </div>
    </div>
    @else
        <div class="alert-info p-3">
            You don't have now any posts please add
        </div>
    @endif
@endsection