routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('/categories','Category\CategoryController');
Route::Resource('/posts','Post\PostController');
Route::Resource('/tags','Tag\TagController');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected  $fillable = ['name'];

    public function posts() {
            return $this->hasMany(Post::class);
        }
        //delete child posts
    protected static function boot() {
        parent::boot();
        static::deleting(function($offer) {
            foreach ($offer->posts as $post) {
                $post->images()->delete();
                $post->tags()->delete();
                $post->tags()->detach();
            }
            $offer->posts()->delete();
        });
    }
}

app/Http/Controllers/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Category;

use App\Contracts\CategoryInterface;
use App\Http\Requests\CategoryCreate;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $category;

    public function __construct(CategoryInterface $category)
    {       //category repo
        $this->category = $category;
    }

    public function index()
    {
        $categories = $this->category->all();
        return view('category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryCreate $request)
    {
       $data =  $this->category->store($request);
       return redirect()->back()->with('message','created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $category = $this->category->edit($id);
       return view('category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illumиnate\Http\Response
     */
    public function update(CategoryCreate $request, $id)
    {
         $category = $this->category->update($id, $request) ;
         return redirect()->back()->with('message','Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data  =  $this->category->delete($id);
        if($data) {
            return response()->json(['id'=>$id]);
        }
  }
}

resources/views/category/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="box box-info col-8">
                <div class="box-header with-border">
                    <h3 class="box-title">Horizontal Form</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('categories.store')}}" method="POST">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="Name" name="name">
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{route('categories.index')}}"  class="btn btn-default">Back</a>
                            <button type="submit" class="btn btn-info pull-right">Add</button>
                            @if(session('message'))
                            <div class="alert-success mt-2 p-2">
                                {{session('message')}}
                            </div>
                            @endif
                            @if($errors->any())
                                <div class="alert-danger mt-2 p-2">
                                    {{$errors->first()}}
                                </div>
                                @endif
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="box box-info col-8">
                <div class="box-header with-border">
                    <h3 class="box-title">Horizontal Form</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('categories.update',$category->id)}}" method="POST">
                    @csrf
                    @method('PUT')

                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="Name" name="name" value="{{$category->name}}">
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{route('categories.index')}}"  class="btn btn-default">Back</a>
                            <button type="submit" class="btn btn-info pull-right">Update</button>
                            @if(session('message'))
                                <div class="alert-success mt-2 p-2">
                                    {{session('message')}}
                                </div>
                            @endif
                            @if($errors->any())
                                <div class="alert-danger mt-2 p-2">
                                    {{$errors->first()}}
                                </div>
                            @endif
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('content')

    <div id="example2_wrapper" class="dataTables_wrapper  dt-bootstrap mt-5">
        <div class="clearfix">
            <h4 class="d-inline-block">Category table</h4>
            <a href="{{route('categories.create')}}" class="btn btn-info pull-right"> Add Category</a>
        </div>
        <div class  ="row">
            <div class="col-sm-6">
                @if(session('message'))
                    <div class="alert-success mt-2 p-2">
                        {{session('message')}}
                    </div>
                @endif
            </div>
            <div class="col-sm-6"></div>
        </div>
        @if($categories->first())
            <div class="row justify-content-center">
                <div class="col-sm-12">
                    <table id="example2" class="table table-bordered table-hover dataTable box box-info" role="grid" aria-describedby="example2_info">
                        <thead>
                        <tr role="row">
                            <th>Id</th>
                            <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" aria-sort="descending">Name</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Last changes</th>
                            <th> Action</th>

                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr role="row" class="odd" data-get="{{$category->id}}">
                                <td>{{$category->id}}</td>
                                <td class="sorting_1"><a href="{{route('categories.edit',$category->id)}}">{{$category->name}}</a>
                                <td>{{$category->updated_at}}</td>
                                <td ><a href="{{route('categories.destroy',$category->id)}}" class="btn btn-danger destroy" data-method="delete"  data-id="{{$category->id}}">Delete</a></td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                </div>
                <div class="col-sm-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                        <ul class="pagination">
                            <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                            <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>
                            <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                        </ul>
                    </div>
                </div>
            </div>
    </div>
    @else
    <div class="alert-info p-3">
        You don't have now any categories please add
    </div>
    @endif
@endsection